version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file search-photos.yaml --s3-bucket frontendbuckettt2 --output-template-file search-photos.yaml
artifacts:
  files:
    - search-photos.yaml
