version: 0.2  
phases:  
  install:
    commands:
      - aws cloudformation package --template-file search-photos.yaml --s3-bucket frontendbuckett2 --output-template-file search-photos.yaml
artifacts:  
  type: zip
  files:
    - search-photos.yaml
